# This is a basic workflow to help you get started with Actions

name: Build App

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      name: Checkout Code
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.2
    
    - name: Restore Nuget Packages
      run: nuget restore hostfile-modifier.sln
    
    - name: Build Application
      run: msbuild hostfile-modifier.sln /p:Configuration=Release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hostfile_modifier
        path: bin/Release
